using Microsoft.EntityFrameworkCore;
using VideoGameApi.Data;
using VideoGameApi.Services;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.

builder.Services.AddControllers();
// Learn more about configuring OpenAPI at https://aka.ms/aspnet/openapi
builder.Services.AddOpenApi();
builder.Services.AddSwaggerGen();

builder.Services.AddDbContext<AppDbContext>(options =>
    options.UseSqlServer(builder.Configuration.GetConnectionString("DefaultConnection")));

builder.Services.AddScoped<IVideoGameCharacterService, VideoGameCharacterService>();
var app = builder.Build();

// Configure the HTTP request pipeline.
if (!app.Environment.IsProduction())
{
    // Generates the native /openapi/v1.json endpoint
    app.MapOpenApi();
    // Enables the middleware for serving generated Swagger as a JSON endpoint
    app.UseSwagger();

    // Enables the interactive Swagger UI
    app.UseSwaggerUI(options =>
    {
        // Point Swagger UI to the OpenAPI document generated by .NET 10
        options.SwaggerEndpoint("/openapi/v1.json", "My API v1");
    });
}

app.UseAuthorization();

app.MapControllers();

app.Run();